In [155]:
import numpy as np
import pandas as pd
houses=pd.read_csv("https://raw.githubusercontent.com/ProfLuciano/cd/gh-pages/data/recife.csv",encoding = "ISO-8859-1")
houses.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
0,1500,-8.059791,-34.889619,4.0,37.0,3.0,3.0,NaN,Boa Vista,Recife,Recife,Pernambuco,apart
1,330000,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,Tamarineira,Recife,Recife,Pernambuco,apart
2,255000,-8.037247,-34.890986,2.0,82.0,1.0,2.0,NaN,Encruzilhada,Recife,Recife,Pernambuco,apart
3,380000,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,Santo Amaro,Recife,Recife,Pernambuco,apart
4,300000,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,Madalena,Recife,Recife,Pernambuco,apart

## Setando campos como categóricos

In [156]:
houses.dtypes

price          int64
latitude     float64
longitude    float64
bedrooms     float64
area         float64
pkspaces     float64
bathrooms    float64
ensuites     float64
suburb        object
district      object
city          object
state         object
type          object
dtype: object

In [157]:
#ajustando tipos dos dados
houses['suburb'] = houses['suburb'].astype('category')
houses['district'] = houses['district'].astype('category')
houses['city'] = houses['city'].astype('category')
houses['state'] = houses['state'].astype('category')
houses['type'] = houses['type'].astype('category')

In [158]:
houses.dtypes

price           int64
latitude      float64
longitude     float64
bedrooms      float64
area          float64
pkspaces      float64
bathrooms     float64
ensuites      float64
suburb       category
district     category
city         category
state        category
type         category
dtype: object

In [159]:
houses['suburb'].cat.categories

Index(['Aflitos', 'Apipucos', 'Areias', 'Arruda', 'Boa Viagem', 'Boa Vista',
       'Campo Grande', 'Casa Amarela', 'Casa Forte', 'CaxangÌÁ',
       'Cidade UniversitÌÁria', 'Coelhos', 'Cohab', 'Cordeiro', 'Curado',
       'Derby', 'Dois IrmÌ£os', 'Encruzilhada', 'Engenho do Meio',
       'Espinheiro', 'EstÌ¢ncia', 'FundÌ£o', 'GraÌ¤as', 'HipÌ_dromo', 'Ibura',
       'Ilha do Retiro', 'Imbiribeira', 'Ipsep', 'Iputinga', 'Jaqueira',
       'Jardim SÌ£o Paulo', 'Madalena', 'Mangabeira', 'Monteiro',
       'Mustardinha', 'Paissandu', 'Parnamirim', 'Pau-Ferro', 'Pina',
       'Ponto de Parada', 'Porto da Madeira', 'PoÌ¤o', 'Prado', 'Rosarinho',
       'San Martin', 'Santana', 'Santo Amaro', 'Santo AntÌ«nio', 'Soledade',
       'SÌ£o JosÌ©', 'Tamarineira', 'TejipiÌ_', 'Torre', 'TorreÌ£o',
       'TorrÌµes', 'Vasco da Gama', 'VÌÁrzea', 'Zumbi'],
      dtype='object')

In [160]:
houses['type'].cat.categories

Index(['apart', 'house'], dtype='object')

In [161]:
houses['type'] = houses['type'].cat.codes

In [162]:
houses.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
0,1500,-8.059791,-34.889619,4.0,37.0,3.0,3.0,NaN,Boa Vista,Recife,Recife,Pernambuco,0
1,330000,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,Tamarineira,Recife,Recife,Pernambuco,0
2,255000,-8.037247,-34.890986,2.0,82.0,1.0,2.0,NaN,Encruzilhada,Recife,Recife,Pernambuco,0
3,380000,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,Santo Amaro,Recife,Recife,Pernambuco,0
4,300000,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,Madalena,Recife,Recife,Pernambuco,0

In [163]:
houses.dtypes

price           int64
latitude      float64
longitude     float64
bedrooms      float64
area          float64
pkspaces      float64
bathrooms     float64
ensuites      float64
suburb       category
district     category
city         category
state        category
type             int8
dtype: object

## Removendo instâncias

In [164]:
houses.shape

(1744, 13)

In [165]:
print(houses.isnull().sum())

price          0
latitude       0
longitude      0
bedrooms       7
area          23
pkspaces      98
bathrooms    206
ensuites     980
suburb         0
district       0
city           0
state          0
type           0
dtype: int64

In [166]:
#remove instâncias com ao menos 1 coluna com dado ausente
houses1 = houses.dropna()
houses1.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
1,330000,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,Tamarineira,Recife,Recife,Pernambuco,0
3,380000,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,Santo Amaro,Recife,Recife,Pernambuco,0
4,300000,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,Madalena,Recife,Recife,Pernambuco,0
5,320000,-8.026516,-34.917791,2.0,50.0,1.0,2.0,1.0,Casa Amarela,Recife,Recife,Pernambuco,0
6,750000,-8.047562,-34.876964,4.0,115.0,2.0,4.0,2.0,Santo Amaro,Recife,Recife,Pernambuco,0

In [167]:
len(houses1)

758

In [168]:
print(houses1.isnull().sum())

price        0
latitude     0
longitude    0
bedrooms     0
area         0
pkspaces     0
bathrooms    0
ensuites     0
suburb       0
district     0
city         0
state        0
type         0
dtype: int64

## Removendo colunas quase vazias

In [169]:
print(houses.isnull().sum())

price          0
latitude       0
longitude      0
bedrooms       7
area          23
pkspaces      98
bathrooms    206
ensuites     980
suburb         0
district       0
city           0
state          0
type           0
dtype: int64

In [170]:
#remove colunas com ao menos 70% de dados ausentes
houses2 = houses.dropna(thresh=0.7*len(houses), axis=1)

In [171]:
houses2.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,suburb,district,city,state,type
0,1500,-8.059791,-34.889619,4.0,37.0,3.0,3.0,Boa Vista,Recife,Recife,Pernambuco,0
1,330000,-8.029595,-34.900372,3.0,86.0,1.0,3.0,Tamarineira,Recife,Recife,Pernambuco,0
2,255000,-8.037247,-34.890986,2.0,82.0,1.0,2.0,Encruzilhada,Recife,Recife,Pernambuco,0
3,380000,-8.047562,-34.876964,3.0,95.0,2.0,3.0,Santo Amaro,Recife,Recife,Pernambuco,0
4,300000,-8.053580,-34.908733,3.0,97.0,1.0,3.0,Madalena,Recife,Recife,Pernambuco,0

In [172]:
print(houses2.isnull().sum())

price          0
latitude       0
longitude      0
bedrooms       7
area          23
pkspaces      98
bathrooms    206
suburb         0
district       0
city           0
state          0
type           0
dtype: int64

## Inserindo dados ausentes em 1 coluna

In [173]:
print(houses2['bathrooms'].mean())
print(houses2['bathrooms'].median())

2.676853055916775
3.0

In [174]:
#adiciona media de banheiros nos dados ausentes de banheiros
houses2['bathrooms'].fillna(houses2['bathrooms'].mean(), inplace=True)

/tmp/ipython-input-174-1943529824.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  houses2['bathrooms'].fillna(houses2['bathrooms'].mean(), inplace=True)
/tmp/ipython-input-174-1943529824.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  houses2['bathrooms'].fillna(houses2['bathrooms'].mean(), inplace=True)

In [175]:
print(houses2.isnull().sum())

price         0
latitude      0
longitude     0
bedrooms      7
area         23
pkspaces     98
bathrooms     0
suburb        0
district      0
city          0
state         0
type          0
dtype: int64

In [176]:
print(houses2['bathrooms'].mean())
print(houses2['bathrooms'].median())

2.676853055916775
2.676853055916775

In [177]:
houses2_numerical = houses2.drop(['suburb', 'district', 'city', 'state'], axis=1)
houses2_numerical.corr(method='spearman')

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,type
price,1.000000,0.142366,0.003046,0.485487,0.492475,0.428939,0.508781,-0.072781
latitude,0.142366,1.000000,-0.159716,-0.037816,0.009346,0.006300,0.101693,0.104560
longitude,0.003046,-0.159716,1.000000,0.000067,-0.042796,-0.082754,0.041270,-0.181911
bedrooms,0.485487,-0.037816,0.000067,1.000000,0.674139,0.676838,0.642759,0.021299
area,0.492475,0.009346,-0.042796,0.674139,1.000000,0.647847,0.525298,0.261902
pkspaces,0.428939,0.006300,-0.082754,0.676838,0.647847,1.000000,0.520335,0.188463
bathrooms,0.508781,0.101693,0.041270,0.642759,0.525298,0.520335,1.000000,0.020843
type,-0.072781,0.104560,-0.181911,0.021299,0.261902,0.188463,0.020843,1.000000

In [178]:
houses_numerical = houses.drop(['suburb', 'district', 'city', 'state'], axis=1)
houses_numerical.corr(method='spearman')

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,type
price,1.000000,0.142366,0.003046,0.485487,0.492475,0.428939,0.559964,0.621447,-0.072781
latitude,0.142366,1.000000,-0.159716,-0.037816,0.009346,0.006300,0.131152,0.082037,0.104560
longitude,0.003046,-0.159716,1.000000,0.000067,-0.042796,-0.082754,0.036063,-0.153205,-0.181911
bedrooms,0.485487,-0.037816,0.000067,1.000000,0.674139,0.676838,0.688388,0.563133,0.021299
area,0.492475,0.009346,-0.042796,0.674139,1.000000,0.647847,0.569009,0.614660,0.261902
pkspaces,0.428939,0.006300,-0.082754,0.676838,0.647847,1.000000,0.559461,0.558090,0.188463
bathrooms,0.559964,0.131152,0.036063,0.688388,0.569009,0.559461,1.000000,0.682480,0.037499
ensuites,0.621447,0.082037,-0.153205,0.563133,0.614660,0.558090,0.682480,1.000000,-0.003763
type,-0.072781,0.104560,-0.181911,0.021299,0.261902,0.188463,0.037499,-0.003763,1.000000

In [179]:
#remove colunas com até 70% de dados ausentes
houses2 = houses.dropna(thresh=0.7*len(houses), axis=1)
#adiciona mediana de banheiros nos dados ausentes de banheiros
houses2['bathrooms'].fillna(houses2['bathrooms'].median(), inplace=True)

/tmp/ipython-input-179-3914036485.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  houses2['bathrooms'].fillna(houses2['bathrooms'].median(), inplace=True)
/tmp/ipython-input-179-3914036485.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  houses2['bathrooms'].fillna(houses2['bathrooms'].median(), inplace=True)

In [180]:
print(houses2['bathrooms'].mean())
print(houses2['bathrooms'].median())

2.7150229357798166
3.0

In [181]:
houses_numerical = houses.drop(['suburb', 'district', 'city', 'state'], axis=1)
houses_numerical.corr(method='spearman')

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,type
price,1.000000,0.142366,0.003046,0.485487,0.492475,0.428939,0.559964,0.621447,-0.072781
latitude,0.142366,1.000000,-0.159716,-0.037816,0.009346,0.006300,0.131152,0.082037,0.104560
longitude,0.003046,-0.159716,1.000000,0.000067,-0.042796,-0.082754,0.036063,-0.153205,-0.181911
bedrooms,0.485487,-0.037816,0.000067,1.000000,0.674139,0.676838,0.688388,0.563133,0.021299
area,0.492475,0.009346,-0.042796,0.674139,1.000000,0.647847,0.569009,0.614660,0.261902
pkspaces,0.428939,0.006300,-0.082754,0.676838,0.647847,1.000000,0.559461,0.558090,0.188463
bathrooms,0.559964,0.131152,0.036063,0.688388,0.569009,0.559461,1.000000,0.682480,0.037499
ensuites,0.621447,0.082037,-0.153205,0.563133,0.614660,0.558090,0.682480,1.000000,-0.003763
type,-0.072781,0.104560,-0.181911,0.021299,0.261902,0.188463,0.037499,-0.003763,1.000000

In [182]:
houses2_numerical = houses2.drop(['suburb', 'district', 'city', 'state'], axis=1)
houses2_numerical.corr(method='spearman')

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,type
price,1.000000,0.142366,0.003046,0.485487,0.492475,0.428939,0.532729,-0.072781
latitude,0.142366,1.000000,-0.159716,-0.037816,0.009346,0.006300,0.131665,0.104560
longitude,0.003046,-0.159716,1.000000,0.000067,-0.042796,-0.082754,0.014587,-0.181911
bedrooms,0.485487,-0.037816,0.000067,1.000000,0.674139,0.676838,0.609528,0.021299
area,0.492475,0.009346,-0.042796,0.674139,1.000000,0.647847,0.532577,0.261902
pkspaces,0.428939,0.006300,-0.082754,0.676838,0.647847,1.000000,0.533391,0.188463
bathrooms,0.532729,0.131665,0.014587,0.609528,0.532577,0.533391,1.000000,0.057812
type,-0.072781,0.104560,-0.181911,0.021299,0.261902,0.188463,0.057812,1.000000

In [183]:
houses['bathrooms'].describe()

count    1538.000000
mean        2.676853
std         1.281568
min         0.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         8.000000
Name: bathrooms, dtype: float64

In [184]:
import random
houses2 = houses.dropna(thresh=0.7*len(houses), axis=1)
#adiciona valor aleatório no intervalo de min e max de banheiros nos dados ausentes de banheiros
houses2['bathrooms'].fillna(random.randint(houses2['bathrooms'].min(),houses2['bathrooms'].max()), inplace=True)

/tmp/ipython-input-184-918309677.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  houses2['bathrooms'].fillna(random.randint(houses2['bathrooms'].min(),houses2['bathrooms'].max()), inplace=True)
/tmp/ipython-input-184-918309677.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  houses2['bathrooms'].fillna(random.randint(houses2['bathrooms'].min(),houses2['bathrooms'].max()), inplace=True)

In [185]:
print(houses2['bathrooms'].mean())
print(houses2['bathrooms'].median())

2.7150229357798166
3.0

## Inserindo dados ausentes em mais de uma coluna

In [186]:
houses=pd.read_csv("https://raw.githubusercontent.com/ProfLuciano/cd/gh-pages/data/recife.csv",encoding = "ISO-8859-1")
houses.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
0,1500,-8.059791,-34.889619,4.0,37.0,3.0,3.0,NaN,Boa Vista,Recife,Recife,Pernambuco,apart
1,330000,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,Tamarineira,Recife,Recife,Pernambuco,apart
2,255000,-8.037247,-34.890986,2.0,82.0,1.0,2.0,NaN,Encruzilhada,Recife,Recife,Pernambuco,apart
3,380000,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,Santo Amaro,Recife,Recife,Pernambuco,apart
4,300000,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,Madalena,Recife,Recife,Pernambuco,apart

In [187]:
houses['suburb'] = houses['suburb'].astype('category')
houses['district'] = houses['district'].astype('category')
houses['city'] = houses['city'].astype('category')
houses['state'] = houses['state'].astype('category')
houses['type'] = houses['type'].astype('category')

In [188]:
houses['suburb'] = houses['suburb'].cat.codes
houses['district'] = houses['district'].cat.codes
houses['city'] = houses['city'].cat.codes
houses['state'] = houses['state'].cat.codes
houses['type'] = houses['type'].cat.codes

In [189]:
houses.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
0,1500,-8.059791,-34.889619,4.0,37.0,3.0,3.0,NaN,5,0,0,0,0
1,330000,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,50,0,0,0,0
2,255000,-8.037247,-34.890986,2.0,82.0,1.0,2.0,NaN,17,0,0,0,0
3,380000,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,46,0,0,0,0
4,300000,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,31,0,0,0,0

In [190]:
!pip install fancyimpute

Requirement already satisfied: fancyimpute in /usr/local/lib/python3.11/dist-packages (0.7.0)
Requirement already satisfied: knnimpute>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (0.1.0)
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.6.1)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.6.6)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.3.2)
Requirement already satisfied: pytest in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (8.3.5)
Requirement already satisfied: nose in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.3.7)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.17.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.11/dist-packages (from knnimpute>=0.1.0->fancyimpute) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (3.6.0)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.11/dist-packages (from cvxpy->fancyimpute) (1.0.4)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from cvxpy->fancyimpute) (0.11.1)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.11/dist-packages (from cvxpy->fancyimpute) (3.2.7.post2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.11/dist-packages (from pytest->fancyimpute) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from pytest->fancyimpute) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.11/dist-packages (from pytest->fancyimpute) (1.6.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from clarabel>=0.5.0->cvxpy->fancyimpute) (1.17.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (75.2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->clarabel>=0.5.0->cvxpy->fancyimpute) (2.22)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->osqp>=0.6.2->cvxpy->fancyimpute) (3.0.2)

In [191]:
from fancyimpute import KNN
houses_knn = KNN(k=3).fit_transform(houses)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Imputing row 1/1744 with 1 missing, elapsed time: 0.522
Imputing row 101/1744 with 0 missing, elapsed time: 0.524
Imputing row 201/1744 with 0 missing, elapsed time: 0.525
Imputing row 301/1744 with 0 missing, elapsed time: 0.526
Imputing row 401/1744 with 2 missing, elapsed time: 0.527
Imputing row 501/1744 with 1 missing, elapsed time: 0.528
Imputing row 601/1744 with 0 missing, elapsed time: 0.529
Imputing row 701/1744 with 0 missing, elapsed time: 0.530
Imputing row 801/1744 with 0 missing, elapsed time: 0.531
Imputing row 901/1744 with 0 missing, elapsed time: 0.532
Imputing row 1001/1744 with 2 missing, elapsed time: 0.536
Imputing row 1101/1744 with 1 missing, elapsed time: 0.541
Imputing row 1201/1744 with 0 missing, elapsed time: 0.543
Imputing row 1301/1744 with 1 missing, elapsed time: 0.546
Imputing row 1401/1744 with 1 missing, elapsed time: 0.549
Imputing row 1501/1744 with 1 missing, elapsed time: 0.551
Imputing row 1601/1744 with 1 missing, elapsed time: 0.552
Imputing row 1701/1744 with 0 missing, elapsed time: 0.554

In [192]:
houses_knn.shape

(1744, 13)

In [193]:
houses3 = pd.DataFrame(data=houses_knn[0:,0:],columns=['price',	'latitude',	'longitude',	'bedrooms',	'area',	'pkspaces',	'bathrooms',	'ensuites', 'suburb'	,'district',	'city', 'state',	'type'])

In [194]:
houses3.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
0,1500.0,-8.059791,-34.889619,4.0,37.0,3.0,3.0,1.0,5.0,0.0,0.0,0.0,0.0
1,330000.0,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,50.0,0.0,0.0,0.0,0.0
2,255000.0,-8.037247,-34.890986,2.0,82.0,1.0,2.0,1.0,17.0,0.0,0.0,0.0,0.0
3,380000.0,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,46.0,0.0,0.0,0.0,0.0
4,300000.0,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,31.0,0.0,0.0,0.0,0.0

In [195]:
print(houses3.isnull().sum())

price        0
latitude     0
longitude    0
bedrooms     0
area         0
pkspaces     0
bathrooms    0
ensuites     0
suburb       0
district     0
city         0
state        0
type         0
dtype: int64

In [196]:
houses3['bathrooms'].describe()

count    1744.000000
mean        2.688170
std         1.260135
min         0.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         8.000000
Name: bathrooms, dtype: float64

## Normalização

In [197]:
houses3.head()

,price,latitude,longitude,bedrooms,area,pkspaces,bathrooms,ensuites,suburb,district,city,state,type
0,1500.0,-8.059791,-34.889619,4.0,37.0,3.0,3.0,1.0,5.0,0.0,0.0,0.0,0.0
1,330000.0,-8.029595,-34.900372,3.0,86.0,1.0,3.0,1.0,50.0,0.0,0.0,0.0,0.0
2,255000.0,-8.037247,-34.890986,2.0,82.0,1.0,2.0,1.0,17.0,0.0,0.0,0.0,0.0
3,380000.0,-8.047562,-34.876964,3.0,95.0,2.0,3.0,1.0,46.0,0.0,0.0,0.0,0.0
4,300000.0,-8.053580,-34.908733,3.0,97.0,1.0,3.0,1.0,31.0,0.0,0.0,0.0,0.0

In [198]:
#preço está dominando o cálculo
dist = np.linalg.norm(houses3.values[1]-houses3.values[2])
print(dist)

75000.0073800006

In [199]:
# normalizando min-max
houses_norm = (houses3 - houses3.min()) / (houses3.max() - houses3.min())
print(houses_norm.head())

      price  latitude  longitude  bedrooms      area  pkspaces  bathrooms  \
0  0.000200  0.524367   0.842831  0.214286  0.007242  0.200000      0.375
1  0.044000  0.683119   0.731592  0.142857  0.036814  0.066667      0.375
2  0.034000  0.642893   0.828691  0.071429  0.034400  0.066667      0.250
3  0.050667  0.588660   0.973751  0.142857  0.042245  0.133333      0.375
4  0.040000  0.557020   0.645092  0.142857  0.043452  0.066667      0.375

       ensuites    suburb  district  city  state  type
0  9.037143e-09  0.087719       NaN   NaN    NaN   0.0
1  1.782421e-08  0.877193       NaN   NaN    NaN   0.0
2  7.973528e-09  0.298246       NaN   NaN    NaN   0.0
3  1.782421e-08  0.807018       NaN   NaN    NaN   0.0
4  1.782421e-08  0.543860       NaN   NaN    NaN   0.0

In [200]:
houses_norm = houses_norm.dropna(thresh=0.7*len(houses), axis=1)
print(houses_norm.head())

      price  latitude  longitude  bedrooms      area  pkspaces  bathrooms  \
0  0.000200  0.524367   0.842831  0.214286  0.007242  0.200000      0.375
1  0.044000  0.683119   0.731592  0.142857  0.036814  0.066667      0.375
2  0.034000  0.642893   0.828691  0.071429  0.034400  0.066667      0.250
3  0.050667  0.588660   0.973751  0.142857  0.042245  0.133333      0.375
4  0.040000  0.557020   0.645092  0.142857  0.043452  0.066667      0.375

       ensuites    suburb  type
0  9.037143e-09  0.087719   0.0
1  1.782421e-08  0.877193   0.0
2  7.973528e-09  0.298246   0.0
3  1.782421e-08  0.807018   0.0
4  1.782421e-08  0.543860   0.0

In [201]:
dist = np.linalg.norm(houses_norm.values[1]-houses_norm.values[2])
print(dist)

0.6058541651037146

In [202]:
# nomarlizando entre 0 e 1
houses['price_norm'] = (houses['price'] - houses['price'].min()) / (houses['price'].max() - houses['price'].min())

In [203]:
houses['price_norm'].describe()

count    1744.000000
mean        0.062007
std         0.079028
min         0.000000
25%         0.000307
50%         0.046667
75%         0.084000
max         1.000000
Name: price_norm, dtype: float64

In [204]:
# normalizando entre -1 e 1
houses['price_norm'] = ((houses['price'] - houses['price'].min()) / (houses['price'].max() - houses['price'].min())*2) -1

In [205]:
houses['price_norm'].describe()

count    1744.000000
mean       -0.875986
std         0.158056
min        -1.000000
25%        -0.999387
50%        -0.906667
75%        -0.832000
max         1.000000
Name: price_norm, dtype: float64

In [206]:
# min-max do scikit
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = MinMaxScaler()
houses['price_norm'] = scaler.fit_transform(houses[['price']])
houses['price_norm'].describe()

count    1744.000000
mean        0.062007
std         0.079028
min         0.000000
25%         0.000307
50%         0.046667
75%         0.084000
max         1.000000
Name: price_norm, dtype: float64

In [207]:
# nomalizando com média e desvio padrão
houses['price_norm'] = (houses['price'] - houses['price'].mean()) / (houses['price'].std())

In [208]:
houses['price_norm'].describe()

count    1.744000e+03
mean    -3.259370e-17
std      1.000000e+00
min     -7.846166e-01
25%     -7.807362e-01
50%     -1.941095e-01
75%      2.782962e-01
max      1.186911e+01
Name: price_norm, dtype: float64

In [209]:
# nomalizando com média e desvio padrão do scikit
scaler = StandardScaler()
houses['price_norm'] = scaler.fit_transform(houses[['price']])
houses['price_norm'].describe()

count    1.744000e+03
mean    -1.629685e-17
std      1.000287e+00
min     -7.848417e-01
25%     -7.809601e-01
50%     -1.941652e-01
75%      2.783760e-01
max      1.187251e+01
Name: price_norm, dtype: float64

## Discretizando área

In [210]:
# discretizando com 10 bins com mesmo intervalo
houses['area_dist'] = pd.cut(houses['area'],10)

In [211]:
houses['area_dist'].value_counts()

area_dist
(23.343, 190.7]     1488
(190.7, 356.4]       193
(356.4, 522.1]        25
(522.1, 687.8]         9
(687.8, 853.5]         4
(853.5, 1019.2]        1
(1516.3, 1682.0]       1
(1019.2, 1184.9]       0
(1184.9, 1350.6]       0
(1350.6, 1516.3]       0
Name: count, dtype: int64

In [212]:
houses['area'].describe()

count    1721.000000
mean      120.782493
std        95.680958
min        25.000000
25%        70.000000
50%        94.000000
75%       139.000000
max      1682.000000
Name: area, dtype: float64

In [213]:
# discretizando com 4 bins com mesmo intervalo (quantiles)
houses['area_dist'] = pd.qcut(houses['area'],4)

In [214]:
houses['area'].describe()

count    1721.000000
mean      120.782493
std        95.680958
min        25.000000
25%        70.000000
50%        94.000000
75%       139.000000
max      1682.000000
Name: area, dtype: float64

In [215]:
houses['area_dist'].value_counts()

area_dist
(24.999, 70.0]     466
(139.0, 1682.0]    429
(94.0, 139.0]      425
(70.0, 94.0]       401
Name: count, dtype: int64